### ISSUE TITLE
Last played game always is CS

### ISSUE THREAD

**Issue by JE-Chen** [FN-FAL113/github-readme-steam-card#7]
Hello in my profile, status always show my last played game is CS
![image](https://github.com/FN-FAL113/github-readme-steam-status/assets/33644111/54d563fd-8d17-47b8-a4d2-04f41701afd8)
actually last played game is Elden ring
![image](https://github.com/FN-FAL113/github-readme-steam-status/assets/33644111/53e3f24e-d747-4ce0-909e-61ad1c1d72ad)
any idea?

**Comment by FN-FAL113** [comment]
Have you tried cleaning browser cache, I'll take look later using your profile

**Comment by JE-Chen** [comment]
After clear everything get same result.

**Comment by JE-Chen** [comment]
![image](https://github.com/FN-FAL113/github-readme-steam-status/assets/33644111/541f4bee-d2eb-4182-8434-7ece1a90089f)

**Comment by FN-FAL113** [comment]
Thank you for providing the needed information. I will take time to debug this and provide a solution asap.

**Comment by FN-FAL113** [comment]
Seems like my api key has no access to your owned games historical data through steam rest. I would like to suggest creating a vercel instance with your own steam api key.

Instructions are here:
[README](https://github.com/FN-FAL113/github-readme-steam-status?tab=readme-ov-file#deploy-your-own-vercel-instance)

**Comment by FN-FAL113** [comment]
Nonetheless, I will provide a band-aid fix for this if owned games playtime data cannot be accessed then it will not display any previously played game.

**Comment by JE-Chen** [comment]
After deploying my own Vercel instance, the status shows the right recent activity.

**Comment by FN-FAL113** [comment]
> After deploying my own Vercel instance, the status shows the right recent activity.

Great to hear! 😃

**Comment by FN-FAL113** [comment]
I would also advise forking the app when creating a vercel instance instead of creating a separate repo.
